# Basic Options
printWidth: 100   # Specifies the maximum line length before code is wrapped
tabWidth: 2       # Sets the number of spaces used for each indentation level
useTabs: false    # Enforces the use of spaces instead of tabs

# Formatting Choices
semi: false       # Disables the requirement for semicolons at the end of statements
singleQuote: true # Enforces the use of single quotes for strings
trailingComma: "es5" # Adds trailing commas where valid in ES5 (arrays and objects)
bracketSpacing: true  # Adds spaces inside curly brackets { } and square brackets [ ] 
arrowParens: "avoid"  # Omits parenthesis around a single argument in arrow functions
singleAttributePerLine: true

# React-Specific
jsxSingleQuote: true  # Requires single quotes for JSX attributes
jsxBracketSameLine: false # Places the > of a multi-line JSX element on its own line 
